In [2]:
import pandas as pd
pd.set_option('display.max_rows', None)

In [3]:
df = pd.read_csv('../ncbi_562_data.csv')
df_other = pd.read_csv('../NORS_20250702.csv')
df_other['Primary Mode'].value_counts()

C:\Users\bryan\AppData\Local\Temp\ipykernel_28768\3490757881.py:2: DtypeWarning: Columns (10,12,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df_other = pd.read_csv('../NORS_20250702.csv')

Primary Mode
Person-to-person                                     32414
Food                                                 24729
Indeterminate/unknown                                 5677
Water                                                 3106
Animal contact                                         655
Environmental contamination other than food/water      132
Name: count, dtype: int64

In [4]:
add = pd.read_csv('ncbi_to_nors_source_match.csv')
df['nors_primary_mode_map'] = df['isolation_source'].copy()

In [5]:
#replace the entries in df['nors_primary_mode_map'] with the cooresponding values in ncbi_to_nors_source_match.csv
df_map = pd.read_csv('ncbi_to_nors_source_match.csv')
#rename the columns to isolation_source and Primary Mode
df_map.columns = ['isolation_source', 'Primary Mode']
df['nors_primary_mode_map'] = df['nors_primary_mode_map'].replace(df_map.set_index('isolation_source')['Primary Mode'].to_dict())

    before                  after
0  missing  Indeterminate/unknown
1    feces                   Food
2    human       Person-to-person
3    urine                  Water
4    stool                   Food

In [69]:

#write a for loop that prints the top value of df['nors_primary_mode_map'].value_counts() asks the user to input a number from 1 to 5,
#and then replaces the top value with the user input
value_counts_index = df['nors_primary_mode_map'].value_counts().index
for i, top_value in enumerate(value_counts_index):
    print(f"Top value {i}: {top_value}")
    user_input = input(f"Enter a number for '{top_value}' (1-6): ")
    if user_input == "1":
        user_input = "Person-to-person"


    elif user_input == "2":
        user_input = "Food"


    elif user_input == "3":
        user_input = "Indeterminate/unknown"


    elif user_input == "4":
        user_input = "Water"


    elif user_input == "5":
        user_input = "Animal contact"

        
    elif user_input == "6":
        user_input = "Environmental contamination other than food/water"
    else:
        break
    add = pd.concat([add, pd.DataFrame({'before': [top_value], 'after': [user_input]})], ignore_index=True)

Top value 0: missing
Top value 1: feces
Top value 2: human
Top value 3: urine
Top value 4: stool
Top value 5: blood
Top value 6: Missing
Top value 7: ground turkey
Top value 8: rectal swab
Top value 9: Faecal
Top value 10: clinical sample
Top value 11: water
Top value 12: Rectal swab
Top value 13: chicken
Top value 14: Not Provided
Top value 15: lung
Top value 16: stool sample
Top value 17: wastewater
Top value 18: UTI
Top value 19: Host-associated strain
Top value 20: food
Top value 21: not collected
Top value 22: sputum
Top value 23: Blood culture
Top value 24: intestine
Top value 25: Ground Beef
Top value 26: urine sample
Top value 27: bovine
Top value 28: anal swab
Top value 29: Unknown
Top value 30: hospital
Top value 31: fecal sample
Top value 32: not applicable
Top value 33: dairy calf feces
Top value 34: environment
Top value 35: clinical
Top value 36: cattle
Top value 37: animal
Top value 38: blood culture
Top value 39: rectum
Top value 40: gut
Top value 41: soil
Top value 42: animal-swine-market swine
Top value 43: turkey
Top value 44: liver
Top value 45: Animal-Turkey-Young Turkey (cecal)
Top value 46: meat
Top value 47: Rectal Swab
Top value 48: rectal
Top value 49: Animal-Swine-Sow (cecal)
Top value 50: chicken breast
Top value 51: river water
Top value 52: Animal-Swine-Market Swine (cecal)
Top value 53: Caecal Content
Top value 54: not provided
Top value 55: cecal content
Top value 56: not available: to be reported later
Top value 57: raw sewage
Top value 58: patient with urinary tract infection
Top value 59: cattle feces
Top value 60: Animal-Chicken-Young Chicken (cecal)
Top value 61: animal-cattle-steer
Top value 62: beef
Top value 63: ground beef
Top value 64: cloacal swab
Top value 65: venous blood
Top value 66: animal-cattle-dairy cow
Top value 67: bloodstream isolates
Top value 68: wound
Top value 69: avian
Top value 70: pig
Top value 71: animal-chicken-young chicken
Top value 72: Animal-Turkey-Young Turkey
Top value 73: culture
Top value 74: product-raw-intact-beef
Top value 75: fecal sample from STEC-infected patient
Top value 76: Faecal sample
Top value 77: Animal-Cattle-Dairy Cow (cecal)
Top value 78: other
Top value 79: comminuted beef
Top value 80: urine from catheter
Top value 81: human - faeces
Top value 82: recto-anal junction
Top value 83: Feces, Gull (Larus spp.)
Top value 84: cattle manure
Top value 85: hospital sewage
Top value 86: Pork Chop
Top value 87: farm
Top value 88: canine
Top value 89: Homo sapiens
Top value 90: patient
Top value 91: human - bacteraemia
Top value 92: environmental
Top value 93: Environmental strain
Top value 94: feces (Bos taurus)
Top value 95: Pig rectal swab
Top value 96: Guyana
Top value 97: pus
Top value 98: animal-cattle-heifer
Top value 99: fecal samples
Top value 100: Cattle feces
Top value 101: cattle fecal samples
Top value 102: Cattle faeces
Top value 103: Dairy milk
Top value 104: pork
Top value 105: chickens
Top value 106: swab
Top value 107: Sewage
Top value 108: dog
Top value 109: bile
Top value 110: Calf fecal composite
Top value 111: farm slurry/meat
Top value 112: Chicken Breasts
Top value 113: Chicken faeces
Top value 114: animal-swine-sow
Top value 115: Commercial Turkey
Top value 116: manure
Top value 117: Human urine
Top value 118: Chicken Thighs
Top value 119: fresh meat
Top value 120: retail chicken
Top value 121: ED Gut
Top value 122: mastitis
Top value 123: animal-cattle-beef cow
Top value 124: human, animal or environmental
Top value 125: feces elk
Top value 126: Pork Chops
Top value 127: blood from patient with bacteremia
Top value 128: cloaca swabs from commercial farm
Top value 129: goat
Top value 130: clinical material
Top value 131: respiratory
Top value 132: Food production environment
Top value 133: infection
Top value 134: Animal-Cattle-Heifer (cecal)
Top value 135: Human faeces
Top value 136: Diseased Organ
Top value 137: bovine manure
Top value 138: Feral swine feces
Top value 139: sheep recto-anal junction
Top value 140: Stools
Top value 141: spinach
Top value 142: feral pig
Top value 143: Not collected
Top value 144: wastewater outflow
Top value 145: chicken feces
Top value 146: sediment
Top value 147: skin
Top value 148: bodily fluid
Top value 149: milk
Top value 150: Pork
Top value 151: Barn Environment
Top value 152: Laboratory
Top value 153: Environment
Top value 154: Sea water
Top value 155: ROAR
Top value 156: Faeces/Manure
Top value 157: fecal swab
Top value 158: Animal-Cattle-Beef Cow (cecal)
Top value 159: Rectal screen
Top value 160: Dairy product
Top value 161: sheep
Top value 162: Chicken Wings
Top value 163: fly
Top value 164: farm environment
Top value 165: surface water
Top value 166: environmental swab
Top value 167: pork meat
Top value 168: feces of feedlot cattle
Top value 169: Poultry slughterhouses
Top value 170: bovine fecal
Top value 171: Animal-Cattle-Steer (cecal)
Top value 172: military dog fecal sample
Top value 173: extraintestinal site
Top value 174: caecum
Top value 175: unknown
Top value 176: rodent
Top value 177: others
Top value 178: Broiler chicken feces
Top value 179: food-producing animal
Top value 180: Cecal Contents
Top value 181: Gut
Top value 182: pens
Top value 183: Human gut
Top value 184: cow paddock straw bedding
Top value 185: wastewater inflow
Top value 186: stray dog feces
Top value 187: human, urine
Top value 188: bovine feces
Top value 189: Pooled cattle faecal samples collected from floor of farm
Top value 190: cloacal sample
Top value 191: pork chop
Top value 192: chicken meat
Top value 193: pig fecal swab
Top value 194: Broiler breeder farm
Top value 195: flour/flour products
Top value 196: feces on street
Top value 197: Rectal sample
Top value 198: oyster
Top value 199: MSF-NIGER
Top value 200: sewage
Top value 201: water from electronic waste dumpsite
Top value 202: female child feces
Top value 203: urine from indwelling catheter
Top value 204: Norway
Top value 205: hide
Top value 206: intestinal tract
Top value 207: outflow from WWTP
Top value 208: VDG
Top value 209: treated wastewater
Top value 210: Poultry
Top value 211: Cattle Hide
Top value 212: small intestine
Top value 213: fecal sample from patient with Hemolytic Uremic Syndrome
Top value 214: stool (Odocoileus hemionus)
Top value 215: Pooled sheep faecal samples collected from floor of farm
Top value 216: Cilantro
Top value 217: Chicken Legs
Top value 218: Rectal swab/stool
Top value 219: LBC
Top value 220: heart
Top value 221: Pooled pig faecal samples collected from floor of farm
Top value 222: Fecal sludge
Top value 223: packaged whole turkey
Top value 224: caecal content
Top value 225: Animal-Calf-Bob Veal (cecal)
Top value 226: inflow to WWTP
Top value 227: chicken carcass
Top value 228: Lettuce
Top value 229: abdomen
Top value 230: infant feces
Top value 231: cerebrospinal fluid
Top value 232: arterial blood
Top value 233: ear
Top value 234: romaine lettuce
Top value 235: tomato
Top value 236: stool (Cervus canadensis)
Top value 237: cucumber
Top value 238: treated sewage
Top value 239: PAR
Top value 240: spleen
Top value 241: faecal
Top value 242: Food (meat)
Top value 243: Catch Basin
Top value 244: fecal matter
Top value 245: male child feces
Top value 246: pig farm
Top value 247: uterus
Top value 248: Pig stool
Top value 249: colonic content of eviscerated cattle
Top value 250: Not applicable
Top value 251: pond water
Top value 252: rectal swab from healthy college student
Top value 253: CIPA

In [9]:
df['nors_primary_mode_map'].value_counts()

nors_primary_mode_map
Food                                                                                                                                                                                                                                 67958
Indeterminate/unknown                                                                                                                                                                                                                66671
Person-to-person                                                                                                                                                                                                                     32849
Water                                                                                                                                                                                                                                25636
Animal contact                                                                                                                                                                                                                       17617
Environmental contamination other than food/water                                                                                                                                                                                     6265
Ground beef                                                                                                                                                                                                                             80
CIPA                                                                                                                                                                                                                                    80
RECTAL SWAB                                                                                                                                                                                                                             79
Pus                                                                                                                                                                                                                                     79
river sediment                                                                                                                                                                                                                          79
poultry                                                                                                                                                                                                                                 79
pleural cavity                                                                                                                                                                                                                          78
In-house environment                                                                                                                                                                                                                    78
Minced meat                                                                                                                                                                                                                             78
Broiler carcasses                                                                                                                                                                                                                       78
Blood (whole)                                                                                                                                                                                                                           78
Pig feces                                                                                                                                                                                                                               77
chicken thigh                                                                                                                                                                                                                           77
Isolated from feces from dairy calf                                                                                                                                                                                                     76
chicken farm                                                                                                                                                                                                                            75
septic tank                                                                                                                                                                                                                             75
vaginal secretion                                                                                                                                                                                                                       75
Animal-Calf-Formula-fed Veal (cecal)                                                                                                                                                                                                    74
chicken manure                                                                                                                                                                                                                          74
brain                                                                                                                                                                                                                                   74
beef carcass                                                                                                                                                                                                                            74
raw hospital sewage                                                                                                                                                                                                                     73
household environment                                                                                                                                                                                                                   73
Product-Raw-Intact-Siluriformes\, Ictaluridae (Catfish)                                                                                                                                                                                 73
Perianal Swab                                                                                                                                                                                                                           73
Caecum                                                                                                                                                                                                                                  72
Diarrhea                                                                                                                                                                                                                                72
chicken cloacal swab                                                                                                                                                                                                                    72
Rectal Swap                                                                                                                                                                                                                             71
Mastitis                                                                                                                                                                                                                                71
Human feces                                                                                                                                                                                                                             70
cheese                                                                                                                                                                                                                                  69
Wild Animal                                                                                                                                                                                                                             67
human faeces                                                                                                                                                                                                                            66
Animal-Calf-Non Formula-fed Veal (cecal)                                                                                                                                                                                                66
Pond                                                                                                                                                                                                                                    66
sepsis                                                                                                                                                                                                                                  66
swine farm                                                                                                                                                                                                                              66
rectal faeces                                                                                                                                                                                                                           66
shrimp                                                                                                                                                                                                                                  65
skinless boneless chicken breast                                                                                                                                                                                                        65
canine feces                                                                                                                                                                                                                            64
raw meat-based diets for companion animals                                                                                                                                                                                              64
beef cattle feces                                                                                                                                                                                                                       64
vaginal swab                                                                                                                                                                                                                            64
Animal-Calf-Formula-fed Veal                                                                                                                                                                                                            64
commercial chicken farm                                                                                                                                                                                                                 64
Clinical material from animal (Neovison vison)                                                                                                                                                                                          63
ESBA                                                                                                                                                                                                                                    63
Ground Pork                                                                                                                                                                                                                             63
Swine manure pit                                                                                                                                                                                                                        62
healthcare wastewater                                                                                                                                                                                                                   62
Bovine hide                                                                                                                                                                                                                             62
Bovine Faeces                                                                                                                                                                                                                           62
ground pork                                                                                                                                                                                                                             61
Human rectal swab                                                                                                                                                                                                                       61
layer cloacal (backyard)                                                                                                                                                                                                                61
Municipal sewage                                                                                                                                                                                                                        60
manure from farm                                                                                                                                                                                                                        60
gut contents                                                                                                                                                                                                                            59
abscess                                                                                                                                                                                                                                 58
manure wastewater                                                                                                                                                                                                                       58
WWTP inflow Grand Prado                                                                                                                                                                                                                 58
Yolk sac                                                                                                                                                                                                                                57
duck                                                                                                                                                                                                                                    57
Retail Poultry                                                                                                                                                                                                                          56
secretion                                                                                                                                                                                                                               56
chicken breasts                                                                                                                                                                                                                         56
Animal-Calf-Bob Veal                                                                                                                                                                                                                    56
ICU patient rectal swab                                                                                                                                                                                                                 56
Chicken meat                                                                                                                                                                                                                            56
the intestinal tract of dog                                                                                                                                                                                                             56
large intestine                                                                                                                                                                                                                         55
retail meat                                                                                                                                                                                                                             55
feces cow                                                                                                                                                                                                                               55
bone marrow                                                                                                                                                                                                                             55
Product-Raw-Intact-Siluriformes                                                                                                                                                                                                         55
lake water                                                                                                                                                                                                                              55
human feces                                                                                                                                                                                                                             55

In [71]:
add.to_csv('ncbi_to_nors_source_match.csv', index=False)
add.head()

    before                  after
0  missing  Indeterminate/unknown
1    feces                   Food
2    human       Person-to-person
3    urine                  Water
4    stool                   Food